name: After master commit

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version-level:
        description: "Release version level"
        required: false
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  create-release:
    if: github.repository == 'oncokb/oncokb-sop'
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: oncokb/github-actions/create-release-action@main
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          version-level: ${{ github.event.inputs['version-level'] }}
